
        <table>
            <tr class="head">
                <th>Portada</th>
                <th>Titulo</th>
                <th>ID de Microsoft</th>
                <th>Género</th>
                <th>Año de lanzamiento</th>
                <th>Clasificación</th>
                <th>Desarrolladores</th>
                <th>Calificación</th>
                <th>Editar</th>
                <th>Eliminar</th>
            </tr>
            <?php 
            foreach($db as $game) {             //itera sobre la tabla recibida
                $thumbnail = $game->thumbnail;  //rellena variables con los datos del objeto sobre el que trabaja en cada iteracion
                $title = $game->title;
                $id = $game->id_game;
                $title_id = $game->title_id;
                $genre = $game->genre;
                $year = $game->year;
                $class = $game->pegi_class;
                $devs = $game->devs;
                $rate = $game->vandal_rating;
            ?>
                <!-- crea una tabla con los datos proporcionados la cual permite editar o eliminar elementos -->
                <tr class="row">
                    <td class="thumbnail-property">
                        <img class="portada" src="<?= $thumbnail ?>" alt="portada">
                    </td>
                    <td class="title-property"><?= $title ?></td>
                    <td class="id-property"><?= $title_id ?></td>
                    <td class="genre-property"><?= $genre ?></td>
                    <td class="year-property"><?= $year ?></td>
                    <td class="class-property"><?= $class ?></td>
                    <td class="devs-property"><?= $devs ?></td>
                    <td class="rating-property"><?= $rate ?></td>
                    <td><a href="edit/<?=$id?>">Editar</a></td>
                    <td><a href="del/<?=$id?>">Eliminar</a></td>
                </tr>
            <?php
            }
            ?>
        </table>
    </section>
</main>