<main>
    <section class="filters">
        <h2>Editar elemento</h2>
        <!-- categorias -->
        <form action="" method="post" class="form">
            <div class="contenedor-filtros"> 
                <!-- INPUT DE ID DEL TITULO -->
                <div class="item-filtro">
                    <label for="title_id" class="label">ID del titulo</label>
                    <input type="text" id="title_id" name="title_id" value="<?php echo $game->title_id ?>">
                </div>
                <!-- INPUT DE CLASIFICACION POR EDAD -->
                <div class="item-filtro">
                    <label for="pegi-filter" class="label">Clasificacion</label>
                    <select name="pegi_class" id="pegi-filter">
                        <option value="NULL"></option>
                        <option value="1" <?php if ($game->pegi_class == 1) {echo ' selected="selected"';} ?>>Sin clasificacion</option>
                        <option value="3" <?php if ($game->pegi_class == 3) {echo ' selected="selected"';} ?>>PEGI 3+</option>
                        <option value="7" <?php if ($game->pegi_class == 7) {echo ' selected="selected"';} ?>>PEGI 7+</option>
                        <option value="12" <?php if ($game->pegi_class == 12) {echo ' selected="selected"';} ?>>PEGI 12+</option>
                        <option value="16" <?php if ($game->pegi_class == 16) {echo ' selected="selected"';} ?>>PEGI 16+</option>
                        <option value="18" <?php if ($game->pegi_class == 18) {echo ' selected="selected"';} ?>>PEGI 18+</option>
                    </select>
                </div>
                <!-- INPUT DE TITULO -->
                <div class="item-filtro">
                    <label for="title" class="label">Titulo</label>
                    <input type="text" id="title" name="title" value="<?php echo $game->title ?>">
                </div>
                <!-- INPUT DE AÑO DE LANZAMIENTO -->
                <div class="item-filtro">
                    <label for="year-filter" class="label">Lanzamiento</label>
                    <select name="release" id="year-filter">
                        <option value="NULL"></option>
                        <option value="2005" <?php if ($game->release == 2005) {echo ' selected="selected"';} ?>>2005</option>
                        <option value="2006" <?php if ($game->release == 2006) {echo ' selected="selected"';} ?>>2006</option>
                        <option value="2007" <?php if ($game->release == 2007) {echo ' selected="selected"';} ?>>2007</option>
                        <option value="2008" <?php if ($game->release == 2008) {echo ' selected="selected"';} ?>>2008</option>
                        <option value="2009" <?php if ($game->release == 2009) {echo ' selected="selected"';} ?>>2009</option>
                        <option value="2010" <?php if ($game->release == 2010) {echo ' selected="selected"';} ?>>2010</option>
                        <option value="2011" <?php if ($game->release == 2011) {echo ' selected="selected"';} ?>>2011</option>
                        <option value="2012" <?php if ($game->release == 2012) {echo ' selected="selected"';} ?>>2012</option>
                        <option value="2013" <?php if ($game->release == 2013) {echo ' selected="selected"';} ?>>2013</option>
                        <option value="2014" <?php if ($game->release == 2014) {echo ' selected="selected"';} ?>>2014</option>
                        <option value="2015" <?php if ($game->release == 2015) {echo ' selected="selected"';} ?>>2015</option>
                        <option value="2016" <?php if ($game->release == 2016) {echo ' selected="selected"';} ?>>2016</option>
                        <option value="2017" <?php if ($game->release == 2017) {echo ' selected="selected"';} ?>>2017</option>
                        <option value="2018" <?php if ($game->release == 2018) {echo ' selected="selected"';} ?>>2018</option>
                        <option value="2019" <?php if ($game->release == 2019) {echo ' selected="selected"';} ?>>2019</option>
                        <option value="2020" <?php if ($game->release == 2020) {echo ' selected="selected"';} ?>>2020</option>
                    </select>
                </div>
                <!-- INPUT DE GENERO -->
                <div class="item-filtro"> 
                    <label for="genre-filter" class="label">Genero</label>
                    <select name="genre" id="genre-filter">
                        <option value="NULL"></option>
                        <option value="Accion" <?php if ($game->genre == "Accion") {echo ' selected="selected"';} ?>>Accion</option>
                        <option value="Aventura" <?php if ($game->genre == "Aventura") {echo ' selected="selected"';} ?>>Aventura</option>
                        <option value="Rol" <?php if ($game->genre == "Rol") {echo ' selected="selected"';} ?>>Rol</option>
                        <option value="Carreras" <?php if ($game->genre == "Carreras") {echo ' selected="selected"';} ?>>Carreras</option>
                        <option value="Disparos" <?php if ($game->genre == "Disparos") {echo ' selected="selected"';} ?>>Disparos</option>
                        <option value="Plataformas" <?php if ($game->genre == "Plataformas") {echo ' selected="selected"';} ?>>Plataformas</option>
                        <option value="Deporte" <?php if ($game->genre == "Deporte") {echo ' selected="selected"';} ?>>Deportes</option>
                        <option value="Pelea" <?php if ($game->genre == "Pelea") {echo ' selected="selected"';} ?>>Lucha</option>
                        <option value="Terror" <?php if ($game->genre == "Terror") {echo ' selected="selected"';} ?>>Horror</option>
                        <option value="Simulacion" <?php if ($game->genre == "Simulacion") {echo ' selected="selected"';} ?>>Simulacion</option>
                        <option value="Supervivencia" <?php if ($game->genre == "Supervivencia") {echo ' selected="selected"';} ?>>Supervivencia</option>
                        <option value="Mundo Abierto" <?php if ($game->genre == "Mundo Abierto") {echo ' selected="selected"';} ?>>Mundo Abierto</option>
                    </select>
                </div>
                <!-- INPUT DE EMPRESA DESARROLLADORA -->
                <div class="item-filtro">
                    <label for="devs-filter" class="label">Desarrolladores</label>
                    <select name="devs" id="devs-filter">
                        <option value="NULL"></option>
                        <option value="Activision" <?php if ($game->devs == "Activision") {echo ' selected="selected"';} ?>>Activision</option>
                        <option value="Ubisoft" <?php if ($game->devs == "Ubisoft") {echo ' selected="selected"';} ?>>Ubisoft</option>
                        <option value="Team17" <?php if ($game->devs == "Team17") {echo ' selected="selected"';} ?>>Team17</option>
                        <option value="Harmonix" <?php if ($game->devs == "Harmonix") {echo ' selected="selected"';} ?>>Harmonix</option>
                        <option value="Bandai Namco" <?php if ($game->devs == "Bandai Namco") {echo ' selected="selected"';} ?>>Bandai Namco</option>
                        <option value="Blizzard" <?php if ($game->devs == "Blizzard") {echo ' selected="selected"';} ?>>Blizzard</option>
                    </select>       
                </div>
                <!-- INPUT DE VALORACION DE CONTENIDO -->
                <div class="item-filtro">
                    <label for="rating-filter" class="label">Valoraciones</label>
                    <select name="vandal_rating" id="rating-filter">
                        <option value="NULL"></option>
                        <option value="1" <?php if ($game->vandal_rating == 1) {echo ' selected="selected"';} ?>>1</option>
                        <option value="2" <?php if ($game->vandal_rating == 2) {echo ' selected="selected"';} ?>>2</option>
                        <option value="3" <?php if ($game->vandal_rating == 3) {echo ' selected="selected"';} ?>>3</option>
                        <option value="4" <?php if ($game->vandal_rating == 4) {echo ' selected="selected"';} ?>>4</option>
                        <option value="5" <?php if ($game->vandal_rating == 5) {echo ' selected="selected"';} ?>>5</option>
                        <option value="6" <?php if ($game->vandal_rating == 6) {echo ' selected="selected"';} ?>>6</option>
                        <option value="7" <?php if ($game->vandal_rating == 7) {echo ' selected="selected"';} ?>>7</option>
                        <option value="8" <?php if ($game->vandal_rating == 8) {echo ' selected="selected"';} ?>>8</option>
                        <option value="9" <?php if ($game->vandal_rating == 9) {echo ' selected="selected"';} ?>>9</option>
                        <option value="10" <?php if ($game->vandal_rating == 10) {echo ' selected="selected"';} ?>>10</option>
                    </select>
                </div>
                <!-- INPUT DE PORTADA -->
                <div class="item-filtro">
                    <label for="thumbnail" class="label">Portada</label>
                    <input type="text" id="thumbnail" name="thumbnail" value="<?=$game->thumbnail?>">
                </div>
            </div>
            <div class="btn btn-submit">
                    <input type="submit" class="submit" value="Confirmar Edicion">
            </div>
            <div class="btn btn-submit">
                    <a href="<?=BASE_URL?>admin" class="submit">Regresar</a>
            </div>
        </form>
    </section>
</main>