<main>
    <section class="login">
        <form action="" method="post">
            <label for="user" class="login-form-item">Nombre de Usuario</label>
            <input type="text" id="user" name="user" class="login-form-item">

            <label for="pass" class="login-form-item">Contraseña</label>
            <input type="text" id="pass" name="pass" class="login-form-item">

            <input type="submit" placeholder="Ingresar" class="login-form-item">
        </form>
    </section>
</main>