        <table>
            <tr class="head">
                <th>Portada</th>
                <th>Titulo</th>
                <th>ID de Microsoft</th>
                <th>Género</th>
                <th>Año de lanzamiento</th>
                <th>Clasificación</th>
                <th>Desarrolladores</th>
                <th>Calificación</th>
            </tr>
        <?php 
            foreach($table as $game) {         //itera sobre la tabla recibida
                $thumbnail = $game->thumbnail; //rellena variables con los datos del objeto sobre el que trabaja en cada iteracion
                $title = $game->title;
                $id = $game->id_game;
                $title_id = $game->title_id;
                $genre = $game->genre;
                $year = $game->year;
                $class = $game->pegi_class;
                $devs = $game->devs;
                $rate = $game->vandal_rating;
        ?>
                <!-- crea una tabla con los datos proporcionados la cual otorga acceso a la pagina singular de cada juego -->
                <tr class="row">
                    <td class="thumbnail-property">
                        <img class="portada" src="<?= $thumbnail ?>" alt="portada">
                    </td>
                    <td class="title-property">
                        <a href="<?=BASE_URL?>game/<?=$id?>"><?= $title ?></a>
                    </td>
                    <td class="title-id-property"><?= $title_id ?></td>
                    <td class="genre-property"><?= $genre ?></td>
                    <td class="year-property"><?= $year ?></td>
                    <td class="class-property"><?= $class ?></td>
                    <td class="devs-property"><?= $devs ?></td>
                    <td class="rating-property"><?= $rate ?></td>
                </tr>
        <?php
            }
        ?>
        </table>
    </section>
</main>