<!DOCTYPE html>
<html lang="es">
    <head>
        <base href="<?php echo BASE_URL ?>">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="css/style.css">
        <title>X360-DB</title>
    </head>
    <body>
        <header>
            <nav class="nav-bar">
                <div class="spacer"></div>
                <div>
                    <a href="home" class="titulo">X360-DB</a>
                </div>
                <?php if($this->user): ?>
                    <a href="logout"><button>Logout</button></a>
                <?php else: ?>
                    <a href="showLogIn"><button>Login</button></a>
                <?php endif; ?>

            </nav>
        </header>